Отредактировал API, по указанным ошибкам.
TkatchGA/Tkachenko-Georgy-ISM-114 pull request #9
Opened 2021-03-26 13:53 UTC by TkatchGA

API отредактировал API по указанным ошибкам, но сам код не трогал.

2021-03-26 20:29 UTC, MarinaPaley requested changes
1. Абсолютно нет понимания о предметной области
2. Скорее такое же понимание об алгоритизации. Почитайте книгу о функциях. Что такое сигнатура, тип возвращаемого результата,

2021-03-26 20:29 UTC, MarinaPaley commented on vector_3d.h
> +    double sum() const;
[стоит лучше понять предметную область](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BA%D1%82%D0%BE%D1%80_(%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F))

2021-03-26 20:29 UTC, MarinaPaley commented on vector_3d.h
> +    std::string compr_vector() const;
не нужно ничего печатать. ответ да или нет, название функции `are_equal(второй вектор)

2021-03-26 20:29 UTC, MarinaPaley commented on vector_3d.h
> +    double sum() const;
я вообще не понимаю, откуда Вы собираетесь второй вектор брать, как он в метод попадет?

2021-03-27 08:58 UTC, TkatchGA commented
Прочитаю указанную вами литературу и постараюсь исправить ошибки. @MarinaPaley

2021-03-27 09:02 UTC, TkatchGA commented on vector_3d.h
> +    double sum() const;
@MarinaPaley В своей программе я создал функцию, которая находиться вне класса, функция спрашивает координаты второго вектора. Дальше в тех методах где, допустим, нужна сумма векторов, я вызываю описанную выше функцию и считываю данные пользователя. Когда делал задание старался придерживаться ТЗ где говорилось, что в класс должны поступать только координаты первого вектора, поэтому все оставшиеся данные запрашивал либо в методах либо вне класса.

2021-03-28 21:48 UTC, MarinaPaley commented on vector_3d.h
> +    double sum() const;
Методы класса (если это не класс-обёртка для взаимодействия с потоками ввода/вывода) не долже оправшивать потоки в _произвольном месте_. Необходимые зависимости класс должен получать/реализовывать _явно_.

2021-04-15 21:02 UTC, merged